#cloud-config
hostname: coreos-1
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDm6baOg9AXEsNZCDwmIr32SEwfhoVvmT4WrsfMtJlPD5zfpGydC0oNbBtmB7DbwANSs79hCgsQw2SGgOumUQMPTCjdrK3DgpUuHZHnLbf/LdOvaM34HzVEwSJ8E24H3272ypdW9LxpNfDp3lwVv9UHQqc1pZ69nQkkEOq7OMozQD8inWDLhMfdXfkGtr8LwYV+Cq9H0jy+V5yAYkC5wMwf/uIVTwfocPZ4wn0iQTj6l/JVInb6A1RsxfhSbHtU+AXYxVa5zi/KJFSExkaIiuKYdTTN6/4jRJuwld7SdJ+f4c8Vh481WqisJCF339lGcVbfoTGdk7JwRNj/rWJrzBCZelVJxohB9eMC5yG6HFWQTb3CwboR6trQ0BK/pcwQMx90UlA8LEdNrGziO8djZIYvT4SWoZEwTe7Wq6s++YNkjs0Jjca+nK0xbci10zgApDUhWhArBdF0hIjVK22Q3g0HizpiwzTohcQfvMyIgrUmXXPAIbFF6Zit57PxzNQn9zHjz+eyznlIh119TnnbRnY7rYL9BT1sEqmb4lpl/H5H4iSfvVLsXrhWu3tXAkBFV1mUcSznfnjUJvLLPVY/p8dc5k4Ux57pOhuhwaGUC2UVjPGWRZw3hvcnqVESOPw8PduP/RWRz6xRH5BgO6YKRvvRhMtTp5+K7CSxgpBuCUcN3Q== boidacarapreta@gmail.com
write_files:
  - path: /etc/hosts
    permissions: 0644
    owner: root
    content: |
      127.0.0.1 localhost
      200.135.37.93 coreos-0 kube-controller kube-apiserver
      200.135.37.94 coreos-1
      200.135.37.95 coreos-2
  - path: /etc/systemd/network/eno-ip.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      Name=eno*
      [Network]
      DNS=200.135.37.72
      DNS=200.135.37.65
      Address=200.135.37.94/24
      Gateway=200.135.37.126
  - path: /etc/systemd/timesyncd.conf
    permissions: 0644
    owner: root
    content: |
      [Time]
      NTP=pool.ntp.br ntp.ufsc.br ntp.cais.rnp.br
  - path: /etc/flannel/options.env
    permissions: 0644
    owner: root
    content: |
      FLANNELD_IFACE=200.135.37.94
      FLANNELD_ETCD_ENDPOINTS=http://200.135.37.93:2379,http://200.135.37.94:2379,http://200.135.37.95:2379
  - path: /etc/kubernetes/manifests/kube-proxy.yaml
    owner: root
    permissions: 0644
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-proxy
      spec:
        hostNetwork: true
        containers:
        - name: kube-proxy
          image: gcr.io/google_containers/hyperkube:v1.3.0
          command:
          - /hyperkube
          - proxy
          - --master=https://200.135.37.93:443
          - --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
          - --proxy-mode=iptables
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: "ssl-certs"
            - mountPath: /etc/kubernetes/worker-kubeconfig.yaml
              name: "kubeconfig"
              readOnly: true
            - mountPath: /etc/kubernetes/ssl
              name: "etc-kube-ssl"
              readOnly: true
        volumes:
          - name: "ssl-certs"
            hostPath:
              path: "/usr/share/ca-certificates"
          - name: "kubeconfig"
            hostPath:
              path: "/etc/kubernetes/worker-kubeconfig.yaml"
          - name: "etc-kube-ssl"
            hostPath:
              path: "/etc/kubernetes/ssl"
  - path: /etc/kubernetes/worker-kubeconfig.yaml
    owner: root
    permissions: 0644
    content: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: local
        cluster:
          certificate-authority: /etc/kubernetes/ssl/ca.pem
      users:
      - name: kubelet
        user:
          client-certificate: /etc/kubernetes/ssl/coreos-1-worker.pem
          client-key: /etc/kubernetes/ssl/coreos-1-worker-key.pem
      contexts:
      - context:
          cluster: local
          user: kubelet
        name: kubelet-context
      current-context: kubelet-context
coreos:
  units:
    - name: systemd-networkd.service
      command: start
      enable: true
    - name: settimezone.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Set the time zone
        Requires=network-online.target
        After=network-online.target
        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone America/Sao_Paulo
        RemainAfterExit=yes
        Type=oneshot
    - name: etcd2.service
      command: start
      enable: true
      drop-ins:
      - name: 10-environment.conf
        content: |
          [Service]
          Environment="ETCD_ADVERTISE_CLIENT_URLS=http://200.135.37.94:2379"
          Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://200.135.37.94:2380"
          Environment="ETCD_INITIAL_CLUSTER=coreos-0=http://200.135.37.93:2380,coreos-1=http://200.135.37.94:2380,coreos-2=http://200.135.37.95:2380"
          Environment="ETCD_INITIAL_CLUSTER_STATE=new"
          Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
          Environment="ETCD_LISTEN_PEER_URLS=http://200.135.37.94:2380"
          Environment="ETCD_NAME=coreos-1"
    - name: flanneld.service
      command: start
      enable: true
      drop-ins:
      - name: 40-ExecStartPre-symlink.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
    - name: docker.service
      command: start
      enable: true
      drop-ins:
      - name: 40-flannel.conf
        content: |
          [Unit]
          Requires=flanneld.service
          After=flanneld.service
    - name: kubelet.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes
        Documentation=https://github.com/coreos/kubernetes
        Documentation=http://kubernetes.io/docs/getting-started-guides/coreos/bare_metal_calico/
        Requires=docker.service
        After=docker.service
        [Service]
        ExecStartPre=/usr/bin/mkdir -p /opt/bin
        ExecStartPre=/usr/bin/curl http://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kubelet -o /opt/bin/kubelet
        ExecStartPre=/usr/bin/curl http://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kubectl -o /opt/bin/kubectl
        ExecStartPre=/usr/bin/chmod 0755 /opt/bin/kubelet /opt/bin/kubectl
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/addons
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl
        ExecStart=/opt/bin/kubelet \
        --port=10250 \
        --address=0.0.0.0 \
        --register-node=true \
        --allow-privileged=true \
        --cluster-dns=10.1.0.2 \
        --cluster-domain=ifsc-sj.local \
        --config=/etc/kubernetes/manifests \
        --hostname-override=coreos-1 \
        --api-servers=https://200.135.37.93:443 \
        --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
        --tls-private-key-file=/etc/kubernetes/ssl/coreos-1-worker-key.pem \
        --tls-cert-file=/etc/kubernetes/ssl/coreos-1-worker.pem \
        --logtostderr=true
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=multi-user.target
