apiVersion: v1
kind: Service
metadata:
  labels:
    app: gluster
    phase: test
    tier: filesystem
    version: v0.1
  name: gluster
spec:
  ports:
    -
      name: gluster-daemon
      port: 24007
      protocol: TCP
      targetPort: 24007
    -
      name: gluster-management
      port: 24008
      protocol: TCP
      targetPort: 24008
    -
      name: gluster-brick
      port: 49152
      protocol: TCP
      targetPort: 49152
  selector:
    app: gluster
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gluster
spec:
  template:
    metadata:
      labels:
        app: gluster
        phase: test
        tier: filesystem
        version: v0.1
    spec:
      containers:
        -
          image: "docker.io/boidacarapreta/gluster:0.1"
          name: gluster
          ports:
            -
              containerPort: 24007
            -
              containerPort: 24008
            -
              containerPort: 49152
          volumeMounts:
            -
              mountPath: /media
              name: persistent
      volumes:
        -
          hostPath:
            path: /media
          name: persistent
