# http://kubernetes.io/docs/user-guide/services/#defining-a-service
# http://docs.openstack.org/developer/magnum/dev/dev-kubernetes-load-balancer.html
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
    phase: test
    tier: frontend
    version: v0.1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
# http://kubernetes.io/docs/user-guide/deployments/
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        phase: test
        tier: frontend
        version: v0.1
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.1
        livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 30
              timeoutSeconds: 1
        ports:
        - containerPort: 80
