apiVersion: v1
kind: Service
metadata:
  externalIPs:
    - "200.135.37.94"
    - "200.135.37.95"
  labels:
    app: nginx
    phase: test
    tier: frontend
    version: v0.1
  name: nginx
spec:
  ports:
    -
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        phase: test
        tier: frontend
        version: v0.1
    spec:
      containers:
        -
          image: "docker.io/nginx:1.11.1"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
          name: nginx
          ports:
            -
              containerPort: 80
